<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <title>IPA Social Network</title>
<?php include_once "html.html";?>
<body>
<div class="container">

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="/">Home</a>
                </li>
                <?php if(!isset($_SESSION['userid'])):?>
                    <li class="nav-item navbar-right">
                        <a class="nav-link" href="/user/login">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/user/register">Register</a>
                    </li>
                <?php endif;?>
                <?php if(isset($_SESSION['userid'])):?>
            </ul>
        </div>
  <div class="dropdown" >
      <button class="dropbtn"><?php echo $_SESSION['Ime']?></button>
        <div class="dropdown-content">
        <a href=/post/PostMenagment>Post menagment</a>
        <a href=/user/UserInfo>User information</a>
        <a class="nav-link" href=/user/logout>Logout</a>
        </div>
  </div>
        <?php endif;?>
    </nav>

</body>
