<?php include 'layout/header.phtml';?>

<?php if(isset($_SESSION['userid'])):?>
<div style="width: fit-content">
<a class="nav-link" href="/post/createPost">Create new post.</a>
</div>

<?php endif;?>
<?php foreach($titles as $title):?>
<div class="row">
    <div class="col">
        <div class="card">
            <div class="card-body">
    <h4><a href=/post/showPost?id=<?php echo $title['id']?>><?php echo $title['naslov'];?></a></h4>
    <br>
                <div class="float-right">
                    <?php if(isset($_SESSION['userid']) && $_SESSION['userid'] == $title['userid']):?>
                        <p style="font-size: 0.95em;"><a href=/post/deletePost?id=<?php echo $title['id']?> onclick="return confirm('Are you sure that you want to delete post?')">Delete</a></p>
                    <?php endif;?>
                </div>
            </div>
        </div>
    </div>
</div>



<?php endforeach;?>