<?php include 'layout/header.phtml';?>

<?php if(isset($_SESSION['userid'])):?>

<a class="nav-link" href="/post/createPost">Create new post.</a>

<?php endif;?>
<?php foreach($titles as $title):?>
<div>
    <a href="/post/showPost"><?php echo $title['naslov'];?></a>
    <br>
    <?php if(isset($_SESSION['userid']) && $_SESSION['userid'] == $title['userid']):?>
    <form action="/post/deletePost" method="post">
        <input type="submit" value="Delete post">
    </form>
    <?php endif;?>
</div>

<?php endforeach;?>
