<?php include "layout/header.phtml";?>
<form action="/post/PostEditEdit" method="post">
    <?php foreach($titles as $title):?>
    <?php if($_GET['id']==$title['id']):?>
        <input type="hidden" name="edit_id" value="<?php echo $_GET['id'];?>">
    <input type="text" value="<?php echo $title['naslov']?>" name="Naslov">
        <br>
        <br>
    <textarea type="text" class="large-centered"  name="Post"><?php echo $title['post']?></textarea>
        <br>
        <button type="submit" class="float-right">Edit</button>
    <?php endif;?>
    <?php endforeach;?>
</form>