<?php include "layout/header.phtml";?>

<?php
foreach($titles as $title)
    foreach($userinfo as $user){
    if($title['id']===$_GET['id']){
        if($title['userid']==$user['id']){
            echo $user['Ime'] . ' ' . $user['Prezime'];
            echo "<br>";
            echo $title['reg_date'];
            echo "<br>";
            echo $title['naslov'];
            echo "<br>";
            echo $title['post'];
        }
    }
}
?>
